// Code generated by Prismic. DO NOT EDIT.

import ImagesSlice from "./ImagesSlice";
import TextSlice from "./TextSlice";
import VideoSlide from "./VideoSlide";

export const components = {
	images_slice: ImagesSlice,
	text_slice: TextSlice,
	video_slide: VideoSlide
};